name: generate-documentation

on: [push]

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: "5"
        number of databases: 1
    - uses: actions/checkout@v2
      with:
        repository: "userdashboard/userdashboard.github.io"
        path: documentation
        persist-credentials: "true"
        token: ${{ secrets.DOCUMENTATION_PAT }}
    - name: Set up as module
      run: |
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm install
        npm version patch
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/storage-redis
        npm install -g mocha
        rm node_modules/@userdashboard/dashboard/*.js
        rm -rf node_modules/@userdashboard/dashboard/src
        cp /home/runner/work/dashboard/dashboard/*.js node_modules/@userdashboard/dashboard
        cp -R /home/runner/work/dashboard/dashboard/src/ node_modules/@userdashboard/dashboard/src/
        echo "global.applicationPath = __dirname" > main.js
        PACKAGE=`cat package.json`
        PACKAGE=${PACKAGE/\"description\"\: \"\"/\"dashboard\": \{ \"modules\"\: \[\"@userdashboard/maxmind-geoip\"\] \}}
        echo $PACKAGE > package.json
    - name: Generate documentation
      run: |
        mocha --grep returns --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-redis"
        REDIS_URL: "redis://localhost:6379"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false   
        GENERATE_RESPONSE: true
        GENERATE_SCREENSHOTS: true
        RESPONSE_PATH: "/home/runner/work/maxmind-geoip/maxmind-geoip/documentation"
        LOG_LEVEL: "info,error,warn,log"
    - name: Publish documentation to Github
      run: |
        cd documentation
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/userdashboard/userdashboard.github.io.git
        git add . --all
        git commit -m "Generated by MaxMind GeoIP module"
        git push origin HEAD:master